# Generated by Django 4.2.16 on 2024-11-22 01:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finlife', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_investment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('predicted_economy', models.CharField(blank=True, choices=[('recession', '하락'), ('growth', '성장'), ('stability', '유지')], max_length=100, null=True)),
                ('risk_preference', models.CharField(blank=True, choices=[('low', '무셔웡'), ('medium', '그냥저냥'), ('high', '바로가~')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_deposits', models.ManyToManyField(blank=True, related_name='recommended_portfolios', to='finlife.depositproducts')),
                ('recommended_savings', models.ManyToManyField(blank=True, related_name='recommended_portfolios', to='finlife.savingproducts')),
                ('selected_deposits', models.ManyToManyField(blank=True, related_name='selected_portfolios', to='finlife.depositproducts')),
                ('selected_savings', models.ManyToManyField(blank=True, related_name='selected_portfolios', to='finlife.savingproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.PositiveIntegerField()),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('investment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('yield_rate', models.FloatField()),
                ('maturity_date', models.DateField(default=datetime.date(2024, 12, 31))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='portfolios.portfolio')),
            ],
        ),
    ]
