# Generated by Django 4.2.16 on 2024-11-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='risk_preference',
            field=models.CharField(blank=True, choices=[('low', '수비적'), ('medium', '보통'), ('high', '공격형')], max_length=100, null=True),
        ),
    ]
