# Generated by Django 4.2.16 on 2024-11-24 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_investment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quantity', models.DecimalField(decimal_places=6, editable=False, max_digits=15)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('volatility', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='recommended_deposits',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='recommended_savings',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='selected_deposits',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='selected_savings',
        ),
        migrations.AddField(
            model_name='stock',
            name='total_investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='stock',
            name='volatility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=6, editable=False, max_digits=15),
        ),
        migrations.DeleteModel(
            name='Bond',
        ),
        migrations.AddField(
            model_name='crypto',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cryptocurrencies', to='portfolios.portfolio'),
        ),
    ]
