# Generated by Django 4.2.16 on 2024-11-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0001_initial'),
        ('portfolios', '0002_crypto_remove_portfolio_recommended_deposits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='recommended_deposits',
            field=models.ManyToManyField(blank=True, null=True, related_name='recommended_to_portfolios', to='finlife.depositproducts'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='recommended_savings',
            field=models.ManyToManyField(blank=True, null=True, related_name='recommended_to_portfolios', to='finlife.savingproducts'),
        ),
    ]
