# Generated by Django 4.2.16 on 2024-11-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_alter_portfolio_risk_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='risk_preference',
            field=models.CharField(blank=True, choices=[('low', '수비적'), ('medium', '보통'), ('high', '공격형')], max_length=100, null=True),
        ),
    ]
