# Generated by Django 4.2.16 on 2024-11-25 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('portfolios', '0003_portfolio_recommended_deposits_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendationlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='recommendationlog',
            name='product',
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='recommended_deposits',
            field=models.ManyToManyField(blank=True, related_name='recommended_to_portfolios', to='finlife.depositproducts'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='recommended_savings',
            field=models.ManyToManyField(blank=True, related_name='recommended_to_portfolios', to='finlife.savingproducts'),
        ),
    ]
