# Generated by Django 4.2.16 on 2024-11-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_alter_recommendationlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='volatility',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
