# Generated by Django 4.2.16 on 2024-11-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoptions',
            name='fin_prdt_cd',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='savingoptions',
            name='fin_prdt_cd',
            field=models.TextField(unique=True),
        ),
    ]
