# Generated by Django 4.2.16 on 2024-11-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproducts',
            name='join_deny',
            field=models.IntegerField(default=1),
        ),
    ]
