# Generated by Django 4.2.16 on 2024-11-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0002_alter_depositoptions_fin_prdt_cd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingoptions',
            name='fin_prdt_cd',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='savingproducts',
            name='fin_prdt_cd',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='depositoptions',
            constraint=models.UniqueConstraint(fields=('product', 'fin_prdt_cd', 'intr_rate_type_nm', 'save_trm'), name='unique_deposit_options'),
        ),
        migrations.AddConstraint(
            model_name='savingoptions',
            constraint=models.UniqueConstraint(fields=('product', 'fin_prdt_cd', 'intr_rate_type_nm', 'save_trm'), name='unique_saving_options'),
        ),
    ]
