# Generated by Django 4.2.16 on 2024-11-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0003_depositproducts_favorited_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositoptions',
            name='dcls_month',
        ),
        migrations.RemoveField(
            model_name='depositproducts',
            name='dcls_month',
        ),
        migrations.RemoveField(
            model_name='depositproducts',
            name='etc_note',
        ),
        migrations.RemoveField(
            model_name='depositproducts',
            name='favorited_by',
        ),
        migrations.RemoveField(
            model_name='depositproducts',
            name='join_deny',
        ),
        migrations.RemoveField(
            model_name='depositproducts',
            name='join_member',
        ),
        migrations.RemoveField(
            model_name='depositproducts',
            name='join_way',
        ),
        migrations.RemoveField(
            model_name='depositproducts',
            name='spcl_cnd',
        ),
    ]
