# Generated by Django 4.2.16 on 2024-11-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0003_alter_savingoptions_fin_prdt_cd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoptions',
            name='fin_prdt_cd',
            field=models.TextField(),
        ),
    ]
