# Generated by Django 4.2.16 on 2024-11-20 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finlife', '0004_remove_depositoptions_dcls_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositoptions',
            name='dcls_month',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='depositproducts',
            name='dcls_month',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='depositproducts',
            name='etc_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depositproducts',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_deposit_products', through='finlife.UserFavoriteProducts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depositproducts',
            name='join_deny',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depositproducts',
            name='join_member',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depositproducts',
            name='join_way',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depositproducts',
            name='spcl_cnd',
            field=models.TextField(blank=True, null=True),
        ),
    ]
